[package]
name = "int_always_ascending"
version = "0.1.0"
edition = "2024"

[dependencies]
int.workspace = true

[dev-dependencies]
arbtest.workspace = true
yare.workspace = true

[lib]
doctest = false
